apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: easybuggy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easybuggy
  template:
    metadata:
      labels:
        app: easybuggy
    spec:
      containers:
      - name: cart
        image: martian1337/easybuggy:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: appnameservice
spec:
  type: NodePort
  selector:
    app: easybuggy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32765
